### ISSUE TITLE
Temporary file for *.wav files never gets deleted

### ISSUE THREAD

**Issue by veN1337** [haumacher/mjSIP#15]
The temporary `*.tmp` file created by the `AudioFile` class, when saving*.wav` files, never gets deleted. Even tough `tmp.delete()` is called. 
You also can not remove it manually because the java process is still holding a reference.

This is because the input stream, which is used to copy the `*.tmp` file to the actual `*.wav` file is never closed. 

It is fixed by closing the `AudioInputStream` after `AudioSystem.write(...)` has written the `*.wav` file (see [here](https://github.com/haumacher/mjSIP/blob/master/mjsip-sound/src/main/java/org/mjsip/sound/AudioFile.java#L130)).

**Comment by haumacher** [comment]
Thanks for your contribution!
